# Generated by Django 5.2.7 on 2025-11-03 20:39

from django.db import migrations
from openedx_authz.constants.roles import LIBRARY_ADMIN, LIBRARY_AUTHOR, LIBRARY_USER
from openedx_authz.api.users import assign_role_to_user_in_scope

def migrate_legacy_permissions(apps, schema_editor):
    """
    Migrate legacy permission data to the new Casbin-based authorization model.
    This function reads legacy permissions from the ContentLibraryPermission model
    and assigns equivalent roles in the new authorization system.
    """
    # ContentLibraryPermission model from the content_libraries app, here is where the legacy permissions are stored
    ContentLibraryPermission = apps.get_model('content_libraries', 'ContentLibraryPermission')

    legacy_permissions = ContentLibraryPermission.objects.select_related('library', 'library__org', 'user').all()
    for permission in legacy_permissions:
        if permission.group:
            # TODO: Consider creating individual role assignments for each user in the group
            print(f"Skipping group-based permission for Group: {permission.group}")
            continue

        # Migrate the permission to the new model

        # Derive equivalent role based on access level
        role = LIBRARY_USER
        if permission.access_level == 'admin':
            role = LIBRARY_ADMIN
        elif permission.access_level == 'author':
            role = LIBRARY_AUTHOR
        elif permission.access_level == 'read':
            role = LIBRARY_USER
        else:
            # This should not happen, log and skip
            # TODO: Should we fail here instead?
            print(f"Unknown access level: {permission.access_level} for User: {permission.user}")
            continue

        # Generating scope based on library identifier
        scope = f"lib:{permission.library.org.name}:{permission.library.slug}"

        print("Migrating permission for User:", permission.user.username,
              "to Role:", role.external_key,
              "in Scope:", scope)

        # TODO: not sure if this can/should be done in an atomic transaction
        assign_role_to_user_in_scope(
            user_external_key=permission.user.username,
            role_external_key=role.external_key,
            scope_external_key=scope
        )


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_authz', '0001_add_casbin_dependency'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_permissions),
    ]
